title='Ryazhenka Tuner'

[@Ряженка]

[Header]
;version=v11.1.0
;creator=Dimasick-git
;about=Мультитул для системных настроек, ПО и оверлеев Nintendo Switch
;credits=Спасибо всем
;ryazhaclk=https://github.com/Dimasick-git/Sys-clk/releases/latest/download/Ryazha-clk.zip

;mode=table
;background=false
;gap=25
;header_indent=true
'Сведения' = ''

[Info]
;mode=table
;spacing=8
;gap=40
'Автор' = 'Dimasick-git'
'Телеграм' = 't.me/Ryazhenkacfw'
'' = ''
'О программе' = 'Мультитул для системы,'
'' = 'оверлеев и хоумбрю'

[Gap]
;mode=table
;background=false
;gap=40

[Header]
;mode=table
;background=false
;header_indent=true
;polling=true
;gap=25
'Тюнинг' = 'Ryazha-clk 3.0.0+'

[Установить Ryazha-clk]
;mode=action
;color=#8B5CF6
try:
   mkdir /config/ryazhahand/downloads/Ryazhenka/
   echo "Скачиваю Ryazha-clk 3.0..."
   download 'https://github.com/Dimasick-git/Sys-clk/releases/latest/download/Ryazha-clk.zip' /config/ryazhahand/downloads/Ryazhenka/Ryazha-clk.zip
   unzip /config/ryazhahand/downloads/Ryazhenka/Ryazha-clk.zip /
   del /config/ryazhahand/downloads/Ryazhenka/
   echo "Ryazha-clk установлен."
   echo "Перезагрузите консоль."
try:
   echo "Ryazha-clk 3.0 ещё не опубликован."

[*Вентиляторы]
;mode=forwarder
package_source './Data/Fan Control/package.ini'

[Gap]
;mode=table
;background=false
;gap=30

[Header]
;mode=table
;background=false
;header_indent=true
;gap=25
'Загрузки' = '{DRIGHT}'

[*Обновления]
;mode=forwarder
package_source './Data/Updater/TunerUpdater.ini'

[*ПО и утилиты]
;mode=forwarder
package_source './Data/Updater/Software.ini'

color=#2277FF

[*Другое]
;mode=forwarder
;mini=true
package_source './Data/Other.ini'

[@Моды]

[Header]
;mode=table
;background=false
;gap=17
'UltraCam для Zelda' = ''

[*Zelda: Слёзы королевства]
;mode=forwarder
;mini=true
package_source './Data/Updater/UltraCam/TotK.ini'
cp './Data/Updater/UltraCam/TotK Init.ini' './Data/Updater/UltraCam/TotK.ini'
cp '/config/Ryazhenka/Mods/TotK.ini' './Data/Updater/UltraCam/TotK.ini'
exec TotK './Data/Updater/UltraCam/boot_package.ini'

[*Zelda: Дыхание природы]
;mode=forwarder
;mini=true
package_source './Data/Updater/UltraCam/BotW.ini'
cp './Data/Updater/UltraCam/BotW Init.ini' './Data/Updater/UltraCam/BotW.ini'
cp '/config/Ryazhenka/Mods/BotW.ini' './Data/Updater/UltraCam/BotW.ini'
exec BotW './Data/Updater/UltraCam/boot_package.ini'

[*Zelda: Эхо мудрости]
;mode=forwarder
;mini=true
package_source './Data/Updater/UltraCam/EoW.ini'
cp './Data/Updater/UltraCam/EoW Init.ini' './Data/Updater/UltraCam/EoW.ini'
cp '/config/Ryazhenka/Mods/EoW.ini' './Data/Updater/UltraCam/EoW.ini'
exec EoW './Data/Updater/UltraCam/boot_package.ini'

[Header]
;mode=table
;background=false
;gap=17
'Сохранение TotK' = ''

[Скачать сохранение]
try:
mkdir /config/ryazhahand/downloads/Ryazhenka/mods/
mkdir /config/Ryazhenka/Mods/
download https://github.com/Dimasick-git/Ryazhenka-resore/releases/download/resources/UltraCam-TotK-Save.zip /config/ryazhahand/downloads/Ryazhenka/mods/downloads.zip
unzip /config/ryazhahand/downloads/Ryazhenka/mods/downloads.zip /
del /config/ryazhahand/downloads/Ryazhenka/mods/
try:
unzip /config/Ryazhenka/Tuner/mod-cache/UltraCam-TotK-Save.zip /
mkdir /config/Ryazhenka/Mods/


[Info]
;mode=table
;spacing=4
'Лес короков' = ''
'Импорт через DBI' = ''
